### ISSUE TITLE
Generating sitemap via CLI throws error and fails

### ISSUE THREAD

**Issue by fsbtmo** [pluginpal/strapi-plugin-sitemap#171]
### Required System information

- Environment: development
- OS: darwin-arm64 (MacOS)
- Strapi Version: 4.25.0
- Node/Yarn Version: npm/10.2.4 node/v20.11.1 darwin arm64 workspaces/false
- Edition: Community
- Database: sqlite

### Describe the bug

The CLI command `npm run sitemap generate` of the sitemap plugin fails on a fresh strapi installation.

```shell
❯ npm run sitemap generate

> stapi-sitemap-test@0.1.0 sitemap
> strapi-sitemap generate

/strapi-sitemap-test/node_modules/@strapi/plugin-i18n/dist/server/index.js:3370
  strapi.api[apiName].routes[modelName].routes.push(localizationRoute);
                                               ^

TypeError: Cannot read properties of undefined (reading 'push')
    at Object.addCreateLocalizationAction (/Users/x/Sites/strapi-sitemap-test/node_modules/@strapi/plugin-i18n/dist/server/index.js:3370:48)
    at /Users/x/Sites/strapi-sitemap-test/node_modules/@strapi/plugin-i18n/dist/server/index.js:2795:22
    at Array.forEach (<anonymous>)
    at extendLocalizedContentTypes (/Users/x/Sites/strapi-sitemap-test/node_modules/@strapi/plugin-i18n/dist/server/index.js:2776:39)
    at Object.register (/Users/x/Sites/strapi-sitemap-test/node_modules/@strapi/plugin-i18n/dist/server/index.js:2743:3)
    at Object.register (/Users/x/Sites/strapi-sitemap-test/node_modules/@strapi/strapi/dist/core/domain/module/index.js:46:46)
    at Object.register (/Users/x/Sites/strapi-sitemap-test/node_modules/@strapi/strapi/dist/core/registries/modules.js:28:19)
    at async Strapi.runLifecyclesFunctions (/Users/x/Sites/strapi-sitemap-test/node_modules/@strapi/strapi/dist/Strapi.js:440:5)
    at async Strapi.register (/Users/x/Sites/strapi-sitemap-test/node_modules/@strapi/strapi/dist/Strapi.js:361:5)
    at async Strapi.load (/Users/x/Sites/strapi-sitemap-test/node_modules/@strapi/strapi/dist/Strapi.js:425:5)

Node.js v20.11.1
``` 

### Steps to reproduce the behavior

1. Add second locale
2. Create simple collection type and add and publish one entry
3. Install and configure `strapi-plugin-sitemap` plugin
- Enter hostname in settings
- Write config in `config/plugins.js`
- Create URL bundle for previously created collection type
- Add `strapi-sitemap` to scripts in `package.json`
4. Run `npm run sitemap generate`

**Comment by boazpoolman** [comment]
Hi @fsbtmo 

Thanks for reporting this issue.
I've been able to reproduce. 
We'll address this as soon as possible.

**Comment by m-farahmand** [comment]
for me got below error
```
D:\Projects\Taha\Taha-Server\node_modules\@strapi\database\dist\index.js:1014
  const { client } = db.config.connection;
          ^

TypeError: Cannot destructure property 'client' of 'db.config.connection' as it is undefined.
    at getDialect (D:\Projects\Taha\Taha-Server\node_modules\@strapi\database\dist\index.js:1014:11)
    at new Database (D:\Projects\Taha\Taha-Server\node_modules\@strapi\database\dist\index.js:6194:20)
    at Database.init (D:\Projects\Taha\Taha-Server\node_modules\@strapi\database\dist\index.js:6180:16)
    at Strapi.bootstrap (D:\Projects\Taha\Taha-Server\node_modules\@strapi\strapi\dist\Strapi.js:372:39)
    at Strapi.load (D:\Projects\Taha\Taha-Server\node_modules\@strapi\strapi\dist\Strapi.js:426:16)
    at async Command.<anonymous> (D:\Projects\Taha\Taha-Server\node_modules\strapi-plugin-sitemap\server\cli.js:25:17)
    at async Command.parseAsync (D:\Projects\Taha\Taha-Server\node_modules\commander\lib\command.js:923:5)

Node.js v18.20.4
error Command failed with exit code 1.
```

**Comment by boazpoolman** [comment]
This issue was fixed and released with [v3.2.1](https://github.com/pluginpal/strapi-plugin-sitemap/releases/tag/3.2.1) of the plugin.

**Comment by kalm42** [comment]
I have 3.2.1 installed and I'm still experiencing the issue. I'm not sure it's this plugin.

So far no one has explained why the issue is happening. I've seen notes about Docker (not relevant to me) and missing env vars (also not relevant). I would be happy to contribute  working hours to fixing this.

**Comment by kalm42** [comment]
> I have 3.2.1 installed and I'm still experiencing the issue. I'm not sure it's this plugin.
> 
> So far no one has explained why the issue is happening. I've seen notes about Docker (not relevant to me) and missing env vars (also not relevant). I would be happy to contribute working hours to fixing this.

Because my standard database is mysql I had the env variables to support that connection which prevented Strapi from using the test connection to sqlite. If I comment out my standard db connection env variables it works. I hope this helps someone.
